my_string = input("Добрый день! Введите имя и фамилию: ")
print ("Количество символов в вашем имени и фамилии:",len(my_string.replace(' ','')))
print(my_string.upper())
print(my_string.lower())
print(my_string.replace(' ',''))
print(my_string[0])
print(my_string[-1])